import Head from "next/head";
import { Inter } from "next/font/google";
import { Header } from "@/components/";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="relative h-[200vh]">
      <Head>
        <title>Movie App | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main>
        {/* Hero */}
        <section></section>
      </main>
    </div>
  );
}
